import { useState, type ReactNode } from "react";
import { useServerFn } from "@tanstack/react-start";
import { submitGuideLead } from "@/lib/leads.functions";
import { submitEnquiry } from "@/lib/enquiries.functions";
import { ArrowRight, Check, ChevronDown, Menu, Phone, Play, Star, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import hero from "@/assets/journey/hero-halong.jpg";
import hoiAn from "@/assets/journey/hoi-an.jpg";
import hanoi from "@/assets/journey/hanoi.jpg";
import kayaking from "@/assets/journey/kayaking.jpg";
import mekong from "@/assets/journey/mekong.jpg";
import andy from "@/assets/journey/andy.jpg";
import tuan from "@/assets/journey/tuan.jpg";
import nhung from "@/assets/journey/nhung.jpg";
import hong from "@/assets/journey/hong.jpg";
import son from "@/assets/journey/son.jpg";
import hiep from "@/assets/journey/hiep.jpg";
import license from "@/assets/journey/license.jpg";
import vita from "@/assets/journey/vita.png";
import vista from "@/assets/journey/vista.jpg";
import pata from "@/assets/journey/pata.jpg";
import payments from "@/assets/journey/payments.png";
import team from "@/assets/journey/team.jpg";

const nav = [["benefits","What You Get"],["comparison","Why Us"],["itinerary","Itinerary"],["videos","Video Stories"],["stays","Hotels"],["founders","The Founders"],["reviews","Reviews"],["faqs","FAQs"]] as const;
const photos = [
  [hero,"Halong Bay","Handcrafted private cruise"],[hoiAn,"Hoi An","Ancient town"],[hanoi,"Hanoi","Heritage lakes"],[kayaking,"Lan Ha Bay","Kayaking"],[mekong,"Mekong Delta","Peaceful canals"],
] as const;
const benefits = [
  ["01","Daily rest","Wake Up Naturally. No 6:00 AM Alarms.","Sleep in until 8:00 AM. Enjoy a hot breakfast and a quiet cup of coffee with zero rush. Your private driver and guide leave only when you are ready. Every afternoon includes a quiet break so you never feel worn out.","Rested, energized & relaxed"],
  ["02","Your own space","Your Own Private Car. Zero Strangers.","Cool air conditioning, cold bottled water, and zero strangers. If someone needs a clean bathroom, wants to stretch their legs, or spots a view to photograph, just say the word.","100% freedom & private comfort"],
  ["03","Food & safety","Hot Fresh Food. Gentle on Your Stomach.","No crowded tour buffets. We choose spotless, handpicked local places with freshly cooked dishes and take care of allergies, mild spices, and dietary wishes.","Delicious dining, zero worry"],
  ["04","Honest guarantee","Zero Factory Shops. 100% Real Sights.","We never trap you in jade, silk, or pearl factories to earn commissions. Every minute is spent enjoying real ancient towns, waterways, and landscapes.","Zero sales pressure, ever"],
  ["05","Personal care","A Kind Local Friend Who Helps With Everything.","Your fluent English-speaking guide carries heavy bags, arranges tickets in advance, and walks at your exact pace. You never feel left behind.","Completely safe & cared for"],
  ["06","Lifelong joy","A Basket of Wonderful Memories to Share.","Make silk lanterns in Hoi An, watch sunset over Halong Bay, and laugh together over iced tea. Return home with photographs and family stories for years.","Pure happiness to take home"],
];
const comparison = [
  ["40 people rushed on a rigid schedule; forced to wake at 6:00 AM.","Your private vehicle and guide. Sleep in or pause for afternoon tea whenever you need."],
  ["Exhausting midday walking in tropical sun, leading to fatigue and restless children.","Morning exploration, shaded lunch, pool or nap break in peak heat, then sunset strolls."],
  ["Compulsory high-pressure shopping stops that consume valuable holiday time.","A strict zero-commission policy. Every hour belongs to your family and authentic culture."],
  ["Impersonal guides speaking hurriedly through megaphones, unable to adapt.","Warm English-speaking storytellers who adjust walking speed and help with luggage."],
  ["Anxiety about street food sanitation and dietary requirements.","Hygienic, family-run restaurants with fresh food and tailored dietary care."],
];
const days = [
  ["Hanoi","Welcome to Hanoi: VIP Airport Fast-Track & Evening Walk","After your long international flight, our airport concierge greets you at the airbridge with VIP fast-track customs clearance. A private driver takes you into Hanoi in a spacious, air-conditioned executive vehicle. Check into your boutique hotel in the quiet French Quarter, rest, then take a gentle lakeside walk before a fragrant welcome dinner.",["Private Transfer (1 hr)","Silk Path Boutique Hanoi","Welcome Dinner Included"]],
  ["Hanoi","Hanoi Heritage: Temple of Literature, Cyclo Ride & Water Puppets","Begin with a relaxed visit to the Temple of Literature, founded in 1070, and its shaded courtyards. Return to your hotel for a two-hour midday rest. Later, take an electric cyclo through the Old Quarter before reserved front-row seats at the Water Puppet Theater.",["Low Physical Exertion","Cyclo Ride Included","VIP Puppet Seats"]],
  ["Lan Ha Bay","Hanoi to Halong Bay / Lan Ha Bay: Board 5-Star Boutique Cruise","Travel by expressway for 2.5 hours with a clean restroom stop. Board a luxury small-ship cruiser into secluded Lan Ha Bay. Lunch is served as emerald waters pass; then take a bamboo boat through Dark & Bright Cave and join an evening cooking demonstration at sunset.",["Overnight Luxury Cruise","Private Balcony Suite","All Meals on Board"]],
  ["Hoi An","Sunrise Tai Chi · Fly to Da Nang & Private Transfer to Ancient Hoi An","Begin with gentle Tai Chi at sunrise. After brunch as the ship returns to harbor, meet your private chauffeur for the transfer to Hanoi airport. A one-hour flight brings you to central Vietnam and a tranquil riverside resort in Hoi An.",["Domestic Flight Included","Anantara Riverside Resort","Brunch Included"]],
  ["Hoi An","Hoi An Living Heritage: Lantern Workshop & Sunset River Sampan","Explore UNESCO-listed Hoi An at an unhurried pace, including 200-year-old merchant houses and the Japanese Bridge. A local family teaches you to fold silk lanterns to take home. At sunset, board a private wooden sampan on the Thu Bon River.",["Hands-on Lantern Workshop","Private Sunset Boat","Zero Shopping Stops"]],
  ["Hoi An","Hoi An Countryside: Tra Que Herb Garden & Relaxed Family Cooking","Ride an electric buggy to Tra Que organic vegetable village. Meet local farmers, enjoy a lemongrass and ginger foot massage, then join a chef in an open-air pavilion to make banh xeo and spring rolls. The afternoon is yours.",["Gentle Herb Foot Massage","Garden Cooking Class","Lunch Included"]],
  ["Hue","Scenic Hai Van Pass Drive · Imperial City of Hue & Royal Garden Villa","Journey north over the spectacular Hai Van Pass. In Hue, explore the Imperial Citadel and serene royal tombs among pine hills. Finish at a restored royal garden house for a quiet tea ceremony with descendants of royal lineage.",["Scenic Private Vehicle Pass","Royal Garden Villa Tea","Hue Heritage Hotel"]],
  ["Saigon","Fly to Ho Chi Minh City · French Landmarks & Rooftop Sunset","Fly south to Saigon. Your private guide introduces the Central Post Office, Opera House, and Reunification Palace gardens. Conclude with sunset refreshments overlooking the skyline from a boutique heritage rooftop.",["Domestic Flight Included","Hotel Grand Saigon / Caravelle","Sunset Drinks Included"]],
  ["Mekong Delta","Mekong Delta: Private Shaded Sampan Cruise & Tropical Orchards","Board a private wooden motorboat, then a hand-rowed sampan beneath water-coconut palms. Taste tropical fruit harvested from family orchards before an easy return to Saigon for your farewell dinner.",["Private Shaded Sampan","Orchard Fruit Tasting","Farewell Dinner Included"]],
  ["Saigon","Leisurely Morning & Private Airport Transfer for Flight Home","Enjoy breakfast at leisure and optional shopping at Ben Thanh Market or the galleries of Dong Khoi. Your private car and guide take you to Tan Son Nhat Airport and assist with check-in.",["Private Departure Transfer","Assisted Airport Check-in","Safe Travels"]],
] as const;
const videos = [
  ["E-X09ld9Ir4","Robert","We made the right decision — extraordinary value!","Everyone is professional, friendly and helpful. Having our own private vehicle and dedicated local guide made all the difference.","Verified Traveler Video"],
  ["9BUEyQiijoo","Thomas & Lorraine Wallace","A company who deserve to do well!","We had the most wonderful holiday through Vietnam, Cambodia and Laos. Tuan gave us faultless service and planned without rushing.","Mature Couple · 43-Day Journey"],
  ["1tBsUAKGhSg","Mrs. Lyndsey Kay Hyman","Experienced driver & caring guide!","Our English-speaking driver and guide were highly experienced and took superb care of us throughout.","Leisure Pacing · Non-Trekking"],
] as const;
const reviews = [
  ["J. D. Reece","Oceanside, California","couples","Sen made sure everything went smoothly — highly recommend!","Absolute Asia did a great job putting together a comprehensive itinerary, but more importantly they were very responsive during our trip. Sen made sure everything went seamlessly."],
  ["Stephen & Margaret M.","United Kingdom · With US Friends","55","Planned an itinerary giving us true flavor of Asia without rushing!","As three mature couples, Tuan patiently helped us plan an itinerary with the true flavor of Asia without rushing. The guides were knowledgeable and hotels were of a great standard."],
  ["Samantha P. & Family","Seattle, Washington","family","Just the right number of days, especially for the kids!","Our 10-day Vietnam trip was amazing. The lantern making and private boat rides kept our children completely engaged."],
  ["Dr. Arthur Sterling & Eleanor","Boston, Massachusetts","55","Total relief for my knee replacement — never felt pushed or rushed.","Curbside drop-offs, elevators in hotels and on our Halong cruise, and comfortable shaded stops made this first-class personal attention."],
  ["Ms. Rana Hajjar","United States","all","Best part of our trip was the total peace of mind we had.","All hotels were comfortable, and having someone waiting at every airport and station made the logistics effortless."],
  ["Mr. Joseph Ajello","United States","all","Fantastic and meticulously arranged by Sen — every handover on time.","Every handover went according to plan over a 30-day journey, with punctual drivers, immaculate vehicles, and caring guides."],
  ["The Gallagher Family","Austin, Texas","family","Grandparents loved the balcony cruise, grandson loved the lantern boats.","Tuan tailored our three-generation schedule so Grandma could nap while the children cooked, then everyone gathered for leisurely dinners."],
  ["Richard & Linda Kowalski","Chicago, Illinois","couples","Zero stomach issues! Clean, authentic restaurants hand-picked for us.","Our guide took us to spotless, family-run restaurants where meals were cooked fresh. Genuine Vietnamese flavors with total peace of mind."],
] as const;
const faqs = [
  ["What happens when we land in Vietnam after our long-haul flight?","Our VIP Fast-Track Arrival Service escorts you through the official priority immigration lane, bypassing queues that can take one to two hours. Clearance typically takes five to ten minutes."],
  ["Is this trip suitable for someone with knee issues or mobility concerns?","Yes. Your private vehicle provides curbside drop-offs, and your guide adjusts every walking pace. Stairs can be skipped and rest stops added whenever needed."],
  ["How do we obtain our Vietnam tourist visa from the US?","US citizens can apply online for a 90-day e-visa for $25 USD. Our team sends step-by-step guidance and can review your application before submission."],
  ["What if someone has dietary restrictions?","We provide translated dietary alert cards in Vietnamese and advise every carefully vetted restaurant in advance about gluten-free, allergy, vegetarian, or other needs."],
  ["Can we customize this itinerary or add extra days?","Absolutely. Add time in Hoi An, continue to Sapa or Angkor Wat, or upgrade your Halong suite. Tell us what matters and we will reshape the journey."],
  ["What is your cancellation and booking deposit policy?","A modest initial deposit secures hotels and flights, with the balance due 30 days before arrival. Flexible postponement is available for health or family events."],
] as const;
const teamGallery = ["03_GS_04164","05_GS_04334","06_GS_04137","07_GS_04296","10_GS_04254","12_GS_04133","13_GS_04168","14_GS_04127","15_GS_04263","18_GS_04280","20_GS_04153","24_GS_04255","25_GS_04198","27_GS_04169","28_GS_04174","29_GS_04243","31_GS_04453","32_GS_04150","33_GS_04141","34_GS_04257","36_GS_04161","37_GS_04512","40_GS_04156","44_GS_04138","45_GS_04506","46_GS_04276","49_GS_04510","50_GS_04487","01_GS_04042","02_GS_04025","04_GS_04075","08_GS_04002","09_GS_04047","11_GS_04055","16_GS_04085","17_GS_04029"];

function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }

export function JourneyPage() {
  const [menuOpen,setMenuOpen]=useState(false);
  const [openDays,setOpenDays]=useState<number[]>([0]);
  const [video,setVideo]=useState("1oI8TyftBj8");
  const [reviewFilter,setReviewFilter]=useState("all");
  const [licenseOpen,setLicenseOpen]=useState(false);
  const [galleryOpen,setGalleryOpen]=useState(false);
  const toggleDay=(i:number)=>setOpenDays((v)=>v.includes(i)?v.filter((x)=>x!==i):[...v,i]);
  return <div className="overflow-x-clip pb-18 md:pb-0">
    <div className="bg-ink text-ivory"><div className="container-editorial grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 py-2.5 text-[10px] uppercase tracking-[0.16em] md:grid-cols-3">
      <a href="https://www.tripadvisor.com" target="_blank" rel="noreferrer" className="truncate text-gold">5.0 TripAdvisor · 450+ reviews</a><span className="hidden text-center md:block">VNAT Licensed · #01-1051/TCDL-GP LHQT</span><a href="tel:+842439276076" className="shrink-0 md:text-right">Hanoi · +84 24 3927 6076</a>
    </div></div>
    <header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur-md"><div className="container-editorial grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 py-4 lg:grid-cols-[auto_1fr_auto]">
      <a href="#top" className="min-w-0"><span className="block truncate font-display text-xl text-ink">Absolute Asia</span><span className="hidden text-[9px] uppercase tracking-[0.2em] text-muted-foreground sm:block">Personalized Experiences</span></a>
      <nav className="hidden justify-center gap-6 lg:flex">{nav.map(([id,label])=><a key={id} href={`#${id}`} className="text-xs text-foreground/75 hover:text-ember">{label}</a>)}</nav>
      <div className="flex items-center gap-2"><Button onClick={()=>scrollTo("inquiry")} className="hidden sm:inline-flex">Customize My Journey</Button><Button variant="ghost" size="icon" aria-label="Open menu" className="lg:hidden" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</Button></div>
    </div>{menuOpen&&<nav className="container-editorial grid border-t border-border py-4 lg:hidden">{nav.map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenuOpen(false)} className="border-b border-border/60 py-3 text-sm">{label}</a>)}</nav>}</header>

    <main id="top">
      <section className="relative min-h-[720px] overflow-hidden md:min-h-[760px]"><img src={hero} alt="Traditional boat among limestone karsts in Halong Bay" width="2560" height="1700" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-hero-veil"/><div className="container-editorial relative flex min-h-[720px] items-end pb-14 pt-28 md:min-h-[760px] md:pb-20"><div className="max-w-4xl text-hero-foreground">
        <p className="text-[11px] uppercase tracking-[0.28em] text-gold">100% tailor-made · No strangers · Your pace</p><h1 className="mt-5 max-w-3xl font-display text-5xl leading-[1.02] text-hero-foreground md:text-7xl">Authentic Vietnam</h1><p className="mt-2 font-display text-2xl text-hero-foreground/95 md:text-4xl">10 Day Private Journey</p>
        <p className="mt-6 max-w-2xl text-base leading-relaxed text-hero-foreground/85 md:text-lg">Thoughtfully paced for discerning travelers, couples and multigenerational families — with private transport, dedicated local care, and zero rush.</p>
        <div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs uppercase tracking-[0.14em] text-hero-foreground/85"><span>10 days / 9 nights</span><span>Private guided · 2–12 guests</span><span>Hanoi · Halong · Hue · Hoi An · Saigon</span></div>
        <div className="mt-7 flex flex-wrap items-center gap-4"><Button size="lg" onClick={()=>scrollTo("inquiry")}>Customize My Journey <ArrowRight/></Button><Button size="lg" variant="light" onClick={()=>scrollTo("journey-film")}><Play/> Watch the Journey</Button><div className="ml-0 border-l border-hero-foreground/30 pl-4 md:ml-2"><span className="block text-[10px] uppercase tracking-[0.16em] text-hero-foreground/70">Private tour from</span><strong className="font-display text-2xl font-normal">$1,890</strong><span className="text-sm"> / person</span></div></div>
        <p className="mt-5 flex items-center gap-2 text-sm"><Star className="size-4 fill-current text-gold"/> 5.0/5.0 · 450+ TripAdvisor reviews</p>
      </div></div></section>

      <section id="journey-film" className="bg-ink py-20 text-ivory md:py-28"><div className="container-editorial grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="text-[11px] uppercase tracking-[0.22em] text-gold">The journey in motion</p><h2 className="mt-4 text-3xl text-ivory md:text-5xl">Ten days, seen from the inside.</h2><p className="mt-6 leading-relaxed text-ivory/70">Meet Vietnam through quiet mornings, living heritage, private waterways, and the people who make each place personal.</p></div><div className="lg:col-span-8"><VideoPlayer id={video} title="Vietnam private journey film"/></div></div></section>
      <section className="bg-cream"><div className="grid grid-cols-2 md:grid-cols-5">{photos.map(([img,place,line],i)=><figure key={place} className={i===4?"col-span-2 md:col-span-1":""}><img src={img} alt={`${place} — ${line}`} loading="lazy" width="700" height="520" className="aspect-[4/3] w-full object-cover"/><figcaption className="border-r border-border px-4 py-4"><strong className="block font-display text-lg font-normal">{place}</strong><span className="text-[10px] uppercase tracking-[0.15em] text-muted-foreground">{line}</span></figcaption></figure>)}</div></section>
      <section className="border-y border-border bg-background"><div className="container-editorial grid grid-cols-2 gap-px bg-border md:grid-cols-4">{[["10 days","9 restful nights"],["Private guided","Only your party"],["Five regions","North to south"],["Fully flexible","Your pace, your interests"]].map(([a,b])=><div key={a} className="bg-background px-5 py-7"><strong className="font-display text-xl font-normal">{a}</strong><p className="mt-1 text-xs uppercase tracking-[0.12em] text-muted-foreground">{b}</p></div>)}</div></section>
      <nav aria-label="Journey sections" className="sticky top-[73px] z-30 hidden overflow-x-auto border-b border-border bg-background/95 backdrop-blur-md md:block"><div className="container-editorial flex gap-8">{nav.slice(0,7).map(([id,label])=><a key={id} href={`#${id}`} className="whitespace-nowrap py-4 text-xs uppercase tracking-[0.14em] text-muted-foreground hover:text-ember">{label}</a>)}</div></nav>

      <Section id="benefits" eyebrow="Thoughtfully paced" title="What You & Your Family Actually Get" intro="The small, practical choices that make a private journey feel effortless."><div className="mt-16 grid gap-x-10 gap-y-12 md:grid-cols-2 lg:grid-cols-3">{benefits.map(([n,k,t,b,f])=><article key={n} className="border-t border-border pt-6"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-[0.2em] text-ember">{k}</span><span className="font-display text-lg text-gold">{n}</span></div><h3 className="mt-5 text-2xl leading-tight">{t}</h3><p className="mt-4 text-sm leading-relaxed text-foreground/75">{b}</p><p className="mt-5 flex gap-2 text-sm"><Check className="size-4 shrink-0 text-ember"/><span><strong>You feel:</strong> {f}</span></p></article>)}</div></Section>

      <Section id="comparison" tone="cream" eyebrow="The balanced pacing difference" title="Private travel should restore you, not exhaust you." intro="Designed around the needs of mature travelers and multigenerational families: less heat, less waiting, and more freedom."><div className="mt-14 overflow-hidden border border-border"><div className="hidden grid-cols-2 bg-ink text-sm text-ivory md:grid"><div className="p-5">Standard Group Tour & DIY Stress</div><div className="border-l border-ivory/20 p-5 text-gold">The Absolute Asia Private Pacing</div></div>{comparison.map(([bad,good],i)=><div key={i} className="grid border-t border-border first:border-t-0 md:grid-cols-2"><div className="bg-background/50 p-5 text-sm leading-relaxed text-muted-foreground"><span className="mb-2 block text-[10px] uppercase tracking-[0.15em] md:hidden">Standard tour</span>{bad}</div><div className="border-t border-border bg-background p-5 text-sm leading-relaxed md:border-l md:border-t-0"><span className="mb-2 block text-[10px] uppercase tracking-[0.15em] text-ember md:hidden">Your private journey</span>{good}</div></div>)}</div></Section>

      <Section id="itinerary" eyebrow="Hanoi to the Mekong" title="10-Day Thoughtfully Paced Itinerary" intro="Every day is 100% customizable. Iconic places are balanced with quiet pauses and authentic local encounters."><div className="mt-10 flex flex-wrap items-center gap-3 text-xs uppercase tracking-[0.12em] text-muted-foreground"><span>Hanoi</span><ArrowRight/><span>Lan Ha Bay</span><ArrowRight/><span>Hoi An</span><ArrowRight/><span>Hue</span><ArrowRight/><span>Saigon & Mekong</span></div><div className="mt-10 flex gap-3"><Button variant="outline" onClick={()=>setOpenDays(days.map((_,i)=>i))}>Expand All</Button><Button variant="ghost" onClick={()=>setOpenDays([])}>Collapse All</Button></div><div className="relative mt-10 border-l border-gold/70">{days.map(([place,title,body,tags],i)=>{const open=openDays.includes(i);return <article key={title} className="relative border-b border-border pl-7 md:pl-12"><span className="absolute -left-3 top-6 grid size-6 place-items-center rounded-full bg-ember text-[10px] text-primary-foreground">{i+1}</span><button type="button" onClick={()=>toggleDay(i)} aria-expanded={open} className="grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-4 py-6 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="min-w-0"><span className="block text-[10px] uppercase tracking-[0.18em] text-ember">Day {i+1} · {place}</span><span className="mt-2 block font-display text-xl leading-tight text-ink md:text-2xl">{title}</span></span><ChevronDown className={`shrink-0 transition-transform ${open?"rotate-180":""}`}/></button>{open&&<div className="pb-7"><p className="max-w-4xl leading-relaxed text-foreground/75">{body}</p><div className="mt-5 flex flex-wrap gap-2">{tags.map((tag)=><span key={tag} className="border border-border bg-cream px-3 py-2 text-xs">{tag}</span>)}</div></div>}</article>})}</div></Section>

      <Section id="videos" tone="ink" eyebrow="Real traveler stories" title="Their journeys, in their own words." intro="Unscripted accounts of private guides, smooth transfers, thoughtful pacing, and care on the ground."><div className="mt-14 grid gap-10 lg:grid-cols-12"><div className="lg:col-span-7"><VideoPlayer id={video} title="Traveler video story"/></div><div className="space-y-3 lg:col-span-5">{videos.map(([id,name,title,quote,context])=><button key={id} type="button" onClick={()=>id&&setVideo(id)} className={`grid w-full grid-cols-[112px_minmax(0,1fr)] gap-4 border p-3 text-left transition-colors ${video===id?"border-gold bg-ivory/10":"border-ivory/20 hover:bg-ivory/5"}`}><img src={`https://i.ytimg.com/vi/${id}/hqdefault.jpg`} alt={`Video review by ${name}`} loading="lazy" className="aspect-video w-full object-cover"/><span className="min-w-0"><span className="text-[9px] uppercase tracking-[0.15em] text-gold">{context}</span><strong className="mt-1 block font-display text-lg font-normal leading-tight text-ivory">{title}</strong><span className="mt-2 hidden text-xs leading-relaxed text-ivory/65 sm:block">“{quote}”</span></span></button>)}</div></div><a href="https://www.youtube.com/channel/UCEZKdt8YGKFgqiRm43OeHoQ/featured" target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 text-sm text-gold">View all video testimonials on YouTube <ArrowRight/></a></Section>

      <Section id="bonuses" tone="cream" eyebrow="Included with your journey" title="VIP Benefits — valued at $420 per couple"><div className="mt-14 grid gap-10 md:grid-cols-3">{[["01","VIP Airport Fast-Track Immigration","Skip the passport lines in Hanoi as your representative escorts you from the airbridge to baggage claim."],["02","Private Hoi An Silk Lantern Boat","An exclusive private wooden boat at twilight, with floating wishing lanterns for your party."],["03","Heritage Coffee & Foot Massage Ritual","A 45-minute herbal lemongrass foot soak and massage, followed by Vietnamese egg coffee."]].map(([n,t,b])=><article key={n} className="border-t border-border pt-6"><span className="font-display text-3xl text-ember">{n}</span><h3 className="mt-4 text-2xl">{t}</h3><p className="mt-3 text-sm leading-relaxed text-foreground/75">{b}</p></article>)}</div></Section>

      <Section id="inclusions" eyebrow="Clear from the start" title="Complete Inclusions: No Hidden Surcharges" intro="Honest, upfront pricing means no unpleasant surprises on the ground."><div className="mt-14 grid gap-12 md:grid-cols-2"><ListBlock title="What is included" items={["9 nights in hand-picked 4-star boutique hotels and a 5-star cruise","Internal flights: Hanoi–Da Nang and Hue–Saigon, with 20kg checked luggage","Private modern air-conditioned vehicle and licensed driver","Dedicated English-speaking private local guides in each region","All stated sightseeing entrance fees, boat tickets, and permits","Daily breakfast and specified lunches and dinners","Chilled bottled water and refreshing wet towels in the vehicle","24/7 concierge support via direct WhatsApp helpline"]}/><ListBlock negative title="What is not included" items={["International airfare between the US and Vietnam","Vietnam e-visa fee: $25 USD per person online","Personal expenses, laundry, telephone, and minibar charges","Travel medical and cancellation insurance","Discretionary tipping for guides and drivers"]}/></div></Section>

      <Section id="stays" tone="cream" eyebrow="Where you rest" title="Handpicked Boutique Accommodations" intro="Chosen for local character, central convenience, and peaceful garden or river settings — never impersonal mega-hotels."><div className="mt-14 grid gap-8 md:grid-cols-3">{[[hanoi,"Silk Path Boutique Hanoi","Boutique Luxury","Quiet lakeview rooms · Family connecting rooms"],[hero,"Indochine Luxury Cruise","5-star small-ship luxury","Private balcony suites · Elevator · Wide sundeck"],[hoiAn,"Anantara Hoi An Resort","5-star riverside haven","Lush gardens · Walk to town · Thu Bon River"]].map(([img,name,rating,line])=><article key={name}><div className="overflow-hidden"><img src={img} alt={`${name} setting`} loading="lazy" className="aspect-[4/3] w-full object-cover transition-transform duration-700 hover:scale-[1.03]"/></div><p className="mt-5 text-[10px] uppercase tracking-[0.18em] text-ember">{rating}</p><h3 className="mt-2 text-2xl">{name}</h3><p className="mt-2 text-sm text-muted-foreground">{line}</p></article>)}</div></Section>

      <Section id="founders" eyebrow="The people behind your journey" title="Founded in Hanoi. Personal by design." intro="Absolute Asia Travel was built on a promise: private journeys should be unhurried, genuinely personal, and shaped by local devotion — never sales quotas or crowded buses."><div className="mt-14 grid gap-10 md:grid-cols-2">{[[andy,"Mr. Lai Duc Anh (Andy)","Co-Founder & Managing Director","Every journey we craft must feel like welcoming cherished family into our homeland — deeply personal, unhurried, and authentic."],[tuan,"Mr. Dong Minh Tuan","Co-Founder & Director of Sales","If you fall in love with a quiet lakeside pagoda or an artisan in Hoi An, our schedule flexes to you."]].map(([img,name,role,quote])=><article key={name} className="grid gap-6 sm:grid-cols-[180px_1fr]"><img src={img} alt={name} loading="lazy" className="aspect-square w-full object-cover"/><div><p className="text-[10px] uppercase tracking-[0.18em] text-ember">{role}</p><h3 className="mt-2 text-2xl">{name}</h3><blockquote className="mt-5 font-display text-xl leading-relaxed text-foreground/80">“{quote}”</blockquote></div></article>)}</div><div className="mt-20 grid items-center gap-12 lg:grid-cols-12"><img src={team} alt="Absolute Asia Travel Hanoi team" loading="lazy" className="w-full lg:col-span-7"/><div className="lg:col-span-5"><p className="eyebrow">Your Hanoi team</p><h3 className="mt-4 text-3xl">The faces behind every seamless mile.</h3><p className="mt-5 leading-relaxed text-foreground/75">Local planners, operations specialists, and senior guides care for your journey as they would welcome close friends home.</p><div className="mt-7 grid grid-cols-2 gap-5">{[[nhung,"Hong Nhung","Travel Specialist"],[hong,"Le Thi Hong","Senior Consultant"],[son,"Doan Quang Son","Operations Lead"],[hiep,"Nguyen Van Hiep","Mekong Guide"]].map(([img,name,role])=><div key={name} className="flex items-center gap-3"><img src={img} alt={name} loading="lazy" className="size-12 shrink-0 rounded-full object-cover"/><span className="min-w-0"><strong className="block truncate text-xs">{name}</strong><span className="text-[10px] text-muted-foreground">{role}</span></span></div>)}</div></div></div><div className="mt-16 border-t border-border pt-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Behind the scenes</p><h3 className="mt-3 text-3xl">Real human connection, every day.</h3></div><Button variant="outline" onClick={()=>setGalleryOpen(!galleryOpen)}>{galleryOpen?"Show Less":"View All 36 Team Moments"}</Button></div><div className="mt-8 grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-6">{teamGallery.slice(0,galleryOpen?36:6).map((file,i)=><img key={file} src={`/images/team/team_${file}.jpg`} alt={`Absolute Asia Travel Hanoi team and operations moment ${i+1}`} loading="lazy" width="1200" height="800" className="aspect-square w-full object-cover"/>)}</div></div></Section>

      <Section id="trust" tone="ink" eyebrow="Licensed and locally accountable" title="Your journey is protected by a licensed Vietnam operator."><div className="mt-14 grid gap-12 lg:grid-cols-12"><div className="lg:col-span-5"><button type="button" onClick={()=>setLicenseOpen(true)} className="group relative block w-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold"><img src={license} alt="Official Vietnam International Tour Operator License GPLHQT" loading="lazy" className="max-h-[520px] w-full object-contain object-left"/><span className="absolute bottom-3 right-3 bg-ink/85 px-3 py-2 text-xs text-ivory">View official license</span></button></div><div className="space-y-6 lg:col-span-7"><h3 className="text-2xl text-ivory">VNAT License #01-1051/TCDL-GP LHQT</h3><p className="leading-relaxed text-ivory/75">Granted by the Vietnam National Administration of Tourism after meeting capital escrow and operating requirements for international tour operators.</p><dl className="grid gap-6 border-t border-ivory/20 pt-6 sm:grid-cols-2"><TrustDetail term="Hanoi headquarters" text="107 Ai Mo Street, Bo De Ward, Long Bien District, Hanoi, Vietnam"/><TrustDetail term="Americas office" text="Paraguay 935, Buenos Aires, Argentina"/><TrustDetail term="Hanoi hotline" text="+84 24 3927 6076"/><TrustDetail term="Americas phone" text="+54 911 6460 1100"/></dl><div className="flex flex-wrap items-center gap-6 border-t border-ivory/20 pt-6"><img src={vita} alt="Vietnam Tourism Association" className="size-16 object-contain"/><img src={vista} alt="Vietnam Society of Travel Agents" className="size-16 object-contain"/><img src={pata} alt="Pacific Asia Travel Association Vietnam Chapter" className="size-16 object-contain"/><img src={payments} alt="Verified payment methods" className="h-7 w-auto"/></div></div></div></Section>

      <Section id="reviews" eyebrow="Verified traveler reviews" title="Care remembered long after the journey." intro="More than 450 five-star reviews across TripAdvisor and Trustpilot from families, retirees, couples, and friends."><div className="mt-10 grid gap-5 border-y border-border py-7 sm:grid-cols-4"><Stat big="5.0" label="TripAdvisor rating"/><Stat big="98%" label="Five-star reviews"/><Stat big="100%" label="Recommended"/><Stat big="4.9" label="Trustpilot · Excellent"/></div><div className="mt-10 flex gap-2 overflow-x-auto pb-2">{[["all","All Reviews"],["55","Travelers 55+"],["couples","Couples & Friends"],["family","Multigenerational Families"]].map(([v,l])=><Button key={v} variant={reviewFilter===v?"default":"outline"} onClick={()=>v&&setReviewFilter(v)} className="shrink-0">{l}</Button>)}</div><div className="mt-12 grid gap-x-12 gap-y-14 md:grid-cols-2">{reviews.filter((r)=>reviewFilter==="all"||r[2]===reviewFilter||r[2]==="all").map(([name,place,,title,body])=><figure key={name} className="border-t border-border pt-7"><div className="flex gap-1 text-gold" aria-label="5 stars">★★★★★</div><blockquote className="mt-5 font-display text-2xl leading-snug">“{title}”</blockquote><p className="mt-4 text-sm leading-relaxed text-foreground/75">“{body}”</p><figcaption className="mt-6 text-xs uppercase tracking-[0.13em]"><strong>{name}</strong><span className="block mt-1 text-muted-foreground">{place}</span></figcaption></figure>)}</div><div className="mt-14"><a href="https://www.tripadvisor.com" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-ember">Read 450+ reviews on TripAdvisor <ArrowRight/></a></div></Section>

      <Section id="faqs" tone="cream" eyebrow="Practical answers" title="Frequently Asked Questions" intro="Clear details to help you plan with confidence."><div className="mt-12 max-w-4xl divide-y divide-border border-y border-border">{faqs.map(([q,a],i)=><details key={q} className="group py-1" open={i===0}><summary className="grid cursor-pointer list-none grid-cols-[minmax(0,1fr)_auto] items-center gap-4 py-5 font-display text-xl"><span>{q}</span><ChevronDown className="shrink-0 transition-transform group-open:rotate-180"/></summary><p className="max-w-3xl pb-6 leading-relaxed text-foreground/75">{a}</p></details>)}</div></Section>

      <section className="py-24 md:py-28"><div className="container-editorial grid items-center gap-14 md:grid-cols-12"><div className="md:col-span-6"><p className="eyebrow">Free Vietnam private travel planning guide</p><h2 className="mt-4 text-4xl md:text-5xl">Planning Vietnam?<br/>Start With Our Private Travel Guide.</h2><p className="mt-6 max-w-xl leading-relaxed text-foreground/75">Get practical route ideas, best travel periods, hotel guidance, pacing advice, and tips from our Hanoi-based travel team.</p></div><div className="border border-border bg-cream p-7 md:col-span-6 md:p-10"><GuideForm/></div></div></section>

      <section id="inquiry" className="bg-cream py-24 md:py-32"><div className="container-editorial grid gap-14 lg:grid-cols-12"><div className="lg:col-span-5"><p className="eyebrow">Begin your private journey</p><h2 className="mt-4 text-4xl md:text-5xl">Customize Your Vietnam Journey</h2><p className="mt-6 leading-relaxed text-foreground/75">Share your dates, travel party, and pace. Our Hanoi team will prepare a free, zero-obligation proposal tailored to you.</p><div className="mt-9 border-t border-border pt-7 text-sm leading-8"><a href="tel:+842439276076" className="block hover:text-ember"><Phone className="mr-2 inline size-4"/>+84 24 3927 6076 · Hanoi</a><a href="tel:+5491164601100" className="block hover:text-ember"><Phone className="mr-2 inline size-4"/>+54 911 6460 1100 · Americas</a><a href="mailto:info@absoluteasiatravel.com" className="block hover:text-ember">info@absoluteasiatravel.com</a></div></div><div className="bg-background p-7 shadow-soft lg:col-span-7 md:p-10"><EnquiryForm/></div></div></section>
    </main>
    <Footer/>
    <div className="fixed inset-x-0 bottom-0 z-50 border-t border-border bg-background p-3 md:hidden"><Button className="w-full" onClick={()=>scrollTo("inquiry")}>Customize My Journey</Button></div>
    {licenseOpen&&<div role="dialog" aria-modal="true" aria-label="Official tour operator license" className="fixed inset-0 z-[60] grid place-items-center bg-overlay p-4" onClick={()=>setLicenseOpen(false)}><button aria-label="Close license" className="absolute right-4 top-4 grid size-11 place-items-center bg-background" onClick={()=>setLicenseOpen(false)}><X/></button><img src={license} alt="Official Vietnam International Tour Operator License GPLHQT" className="max-h-[90vh] max-w-[90vw] object-contain" onClick={(e)=>e.stopPropagation()}/></div>}
  </div>;
}

function Section({id,eyebrow,title,intro,children,tone="light"}:{id:string;eyebrow:string;title:string;intro?:string;children:ReactNode;tone?:"light"|"cream"|"ink"}) { return <section id={id} className={`${tone==="cream"?"bg-cream":tone==="ink"?"bg-ink text-ivory":"bg-background"} scroll-mt-32 py-24 md:py-32`}><div className="container-editorial"><div className="max-w-3xl"><p className={tone==="ink"?"text-[11px] uppercase tracking-[0.22em] text-gold":"eyebrow"}>{eyebrow}</p><h2 className={`mt-4 text-4xl leading-tight md:text-5xl ${tone==="ink"?"text-ivory":""}`}>{title}</h2>{intro&&<p className={`mt-6 max-w-2xl leading-relaxed ${tone==="ink"?"text-ivory/70":"text-foreground/75"}`}>{intro}</p>}</div>{children}</div></section> }
function VideoPlayer({id,title}:{id:string;title:string}) { const [loaded,setLoaded]=useState(false); return <div className="aspect-video w-full overflow-hidden bg-ink-soft">{loaded?<iframe className="h-full w-full" src={`https://www.youtube-nocookie.com/embed/${id}?autoplay=1&rel=0`} title={title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<button type="button" onClick={()=>setLoaded(true)} className="group relative h-full w-full"><img src={`https://i.ytimg.com/vi/${id}/maxresdefault.jpg`} onError={(e)=>{e.currentTarget.src=`https://i.ytimg.com/vi/${id}/hqdefault.jpg`}} alt={`${title} thumbnail`} className="h-full w-full object-cover opacity-80"/><span className="absolute inset-0 grid place-items-center"><span className="grid size-16 place-items-center rounded-full bg-primary text-primary-foreground transition-transform group-hover:scale-105"><Play className="ml-1"/></span></span></button>}</div> }
function ListBlock({title,items,negative=false}:{title:string;items:string[];negative?:boolean}) { return <div><h3 className="text-2xl">{negative?"Not included":"Included"}</h3><ul className="mt-6 divide-y divide-border border-y border-border">{items.map((x)=><li key={x} className="flex gap-3 py-4 text-sm leading-relaxed"><span className={negative?"text-muted-foreground":"text-ember"}>{negative?"—":<Check className="size-4"/>}</span>{x}</li>)}</ul></div> }
function TrustDetail({term,text}:{term:string;text:string}) { return <div><dt className="text-[10px] uppercase tracking-[0.18em] text-gold">{term}</dt><dd className="mt-2 text-sm leading-relaxed text-ivory/80">{text}</dd></div> }
function Stat({big,label}:{big:string;label:string}) { return <div><strong className="font-display text-3xl font-normal text-ember">{big}</strong><span className="mt-1 block text-[10px] uppercase tracking-[0.14em] text-muted-foreground">{label}</span></div> }
function EnquiryForm() {
  const submit = useServerFn(submitEnquiry);
  const [sent,setSent]=useState(false);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  if (sent) return <div className="py-16 text-center"><p className="eyebrow">Thank you</p><h3 className="mt-4 text-3xl">Your journey brief has been received.</h3><p className="mt-4 text-muted-foreground">A travel specialist will be in touch to discuss your private Vietnam journey.</p></div>;
  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const f = new FormData(e.currentTarget);
    const get = (k: string) => String(f.get(k) ?? "").trim();
    const fullName = get("name"), email = get("email");
    if (!fullName) { setError("Please enter your name."); return; }
    if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email) || email.length > 255) { setError("Please enter a valid email address."); return; }
    setError(""); setBusy(true);
    try {
      const res = await submit({ data: { fullName: fullName.slice(0,120), email, phone: get("phone").slice(0,60), guests: get("guests").slice(0,60), travelDates: get("dates").slice(0,120), wishes: get("wishes").slice(0,3000), source: "vietnam-private-journey" } });
      if (res.ok) setSent(true); else setError(res.error);
    } catch { setError("We could not send your enquiry. Please try again, or email info@absoluteasiatravel.com."); }
    finally { setBusy(false); }
  };
  return <form onSubmit={onSubmit} noValidate className="grid gap-5 sm:grid-cols-2"><Field label="Your Full Name" name="name" required/><Field label="Email Address" name="email" type="email" required/><Field label="Phone / WhatsApp" name="phone" type="tel" required/><label className="grid gap-2 text-sm">Guests<select name="guests" className="min-h-12 border border-input bg-background px-3 focus:outline-none focus:ring-2 focus:ring-ring"><option>2 Adults</option><option>3–4 (Family)</option><option>5–8 (Multi-Gen)</option><option>9+ (Private Group)</option></select></label><Field label="Estimated Travel Month / Year" name="dates" placeholder="e.g. October 2026" full/><label className="grid gap-2 text-sm sm:col-span-2">Special Wishes / Pacing / Mobility<textarea name="wishes" rows={5} placeholder="Tell us what would make this journey right for you." className="border border-input bg-background px-3 py-3 focus:outline-none focus:ring-2 focus:ring-ring"/></label>{error&&<p role="alert" className="text-sm text-ember sm:col-span-2">{error}</p>}<div className="sm:col-span-2"><Button type="submit" size="lg" disabled={busy} className="w-full">{busy?"Sending…":<>Get Your Free Custom Itinerary <ArrowRight/></>}</Button><p className="mt-3 text-center text-xs text-muted-foreground">No payment required · Zero spam · Your details are used only for your journey proposal.</p></div></form>;
}
function GuideForm() {
  const submit = useServerFn(submitGuideLead);
  const [sent,setSent]=useState(false);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  if (sent) return <div><p className="eyebrow">Thank you</p><h3 className="mt-4 text-3xl">Your guide is on its way.</h3><p className="mt-4 text-foreground/75">Ready to go further?</p><Button className="mt-6" onClick={()=>scrollTo("inquiry")}>Customize My Vietnam Journey</Button></div>;
  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = new FormData(e.currentTarget);
    const firstName = String(form.get("guide-name") ?? "").trim();
    const email = String(form.get("guide-email") ?? "").trim();
    if (!firstName) { setError("Please enter your first name."); return; }
    if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email) || email.length > 255) { setError("Please enter a valid email address."); return; }
    setError(""); setBusy(true);
    try {
      const res = await submit({ data: { firstName: firstName.slice(0,80), email, source: "vietnam-private-journey" } });
      if (res.ok) setSent(true); else setError(res.error);
    } catch { setError("We could not save your request. Please try again."); }
    finally { setBusy(false); }
  };
  return <form onSubmit={onSubmit} className="space-y-5" noValidate><Field label="First Name" name="guide-name" required/><Field label="Email" name="guide-email" type="email" required/>{error&&<p role="alert" className="text-sm text-ember">{error}</p>}<Button type="submit" disabled={busy} className="w-full">{busy?"Sending…":<>Get My Free Vietnam Guide <ArrowRight/></>}</Button><p className="text-xs text-muted-foreground">Useful planning notes only. No spam.</p></form>;
}
function Field({label,name,type="text",required=false,placeholder,full=false}:{label:string;name:string;type?:string;required?:boolean;placeholder?:string;full?:boolean}) { return <label className={`grid gap-2 text-sm ${full?"sm:col-span-2":""}`}>{label}{required&&<span className="sr-only">required</span>}<input name={name} type={type} required={required} placeholder={placeholder} className="min-h-12 border border-input bg-background px-3 focus:outline-none focus:ring-2 focus:ring-ring"/></label> }
export function Footer(){return <footer className="bg-ink text-ivory"><div className="container-editorial grid gap-12 py-20 md:grid-cols-12"><div className="md:col-span-5"><p className="font-display text-2xl">Absolute Asia</p><p className="mt-1 text-[10px] uppercase tracking-[0.2em] text-gold">Private Journeys · Since 2010</p><p className="mt-6 max-w-md text-sm leading-relaxed text-ivory/70">Bespoke private journeys through Vietnam, Cambodia, Laos, Thailand and Myanmar for travelers seeking comfort, cultural depth, and zero rush.</p></div><div className="md:col-span-3"><p className="text-[10px] uppercase tracking-[0.18em] text-gold">Explore</p><ul className="mt-5 space-y-3 text-sm text-ivory/75"><li><a href="/vietnam">Vietnam Collection</a></li>{nav.slice(1).map(([id,label])=><li key={id}><a href={`/#${id}`}>{label}</a></li>)}</ul></div><div className="md:col-span-4"><p className="text-[10px] uppercase tracking-[0.18em] text-gold">Speak with a specialist</p><div className="mt-5 space-y-3 text-sm text-ivory/75"><p>107 Ai Mo St., Bo De, Long Bien, Hanoi</p><a className="block" href="tel:+842439276076">+84 24 3927 6076</a><a className="block" href="mailto:info@absoluteasiatravel.com">info@absoluteasiatravel.com</a><p>VNAT License #01-1051/TCDL-GP LHQT</p></div></div></div><div className="border-t border-ivory/15"><div className="container-editorial flex flex-col gap-3 py-6 text-xs text-ivory/55 sm:flex-row sm:justify-between"><p>© 2010–2026 Absolute Asia Travel. All rights reserved.</p><div className="flex gap-5"><a href="https://absoluteasiatravel.com/privacy-policy/">Privacy Policy</a><a href="https://absoluteasiatravel.com/booking-conditions/">Booking Conditions</a></div></div></div></footer>}

export { faqs };
